---
- name: Linux upgrade OS rhel{7,8}
  hosts: nodes:quorum
  become: yes
  become_method: sudo
  become_user: root
  remote_user: ansible
  gather_facts: yes
  roles:
    - role: roles/linux-os-upgrade
        
...
